
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class Booty : Luban.BeanBase
{
    public Booty(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
        MianItemId = _buf.ReadInt();
        MianItemId_Ref = null;
    }

    public static Booty DeserializeBooty(ByteBuf _buf)
    {
        return new item.Booty(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 主奖励
    /// </summary>
    public readonly int MianItemId;
    public item.Item MianItemId_Ref;
   
    public const int __ID__ = 894746892;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        MianItemId_Ref = tables.TbItem.GetOrDefault(MianItemId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "mianItemId:" + MianItemId + ","
        + "}";
    }
}

}

