
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.res
{
public sealed partial class ModelConfig : Luban.BeanBase
{
    public ModelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        Path = _buf.ReadString();
    }

    public static ModelConfig DeserializeModelConfig(ByteBuf _buf)
    {
        return new res.ModelConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 模型路径
    /// </summary>
    public readonly string Path;
   
    public const int __ID__ = 200724317;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "path:" + Path + ","
        + "}";
    }
}
}

