
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.res
{
public partial class TbModel
{
    private readonly System.Collections.Generic.Dictionary<int, res.ModelConfig> _dataMap;
    private readonly System.Collections.Generic.List<res.ModelConfig> _dataList;
    
    public TbModel(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, res.ModelConfig>();
        _dataList = new System.Collections.Generic.List<res.ModelConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            res.ModelConfig _v;
            _v = global::GameConfig.res.ModelConfig.DeserializeModelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, res.ModelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<res.ModelConfig> DataList => _dataList;

    public res.ModelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public res.ModelConfig Get(int key) => _dataMap[key];
    public res.ModelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

