
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BuffConfig : Luban.BeanBase
{
    public BuffConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuffEffects = new System.Collections.Generic.List<CBuffEffect>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { CBuffEffect _e0;  _e0 = global::GameConfig.CBuffEffect.DeserializeCBuffEffect(_buf); BuffEffects.Add(_e0);}}
        TargetType = (ETargetType)_buf.ReadInt();
        TriggerType = (ETriggerType)_buf.ReadInt();
        StatusId = _buf.ReadInt();
        StatusId_Ref = null;
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TargetParams = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); TargetParams.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ConditionParams = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); ConditionParams.Add(_e0);}}
        Duration = _buf.ReadFloat();
        TickInterval = _buf.ReadFloat();
        MaxStacks = _buf.ReadInt();
    }

    public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
    {
        return new battle.BuffConfig(_buf);
    }

    /// <summary>
    /// BuffID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// Buff效果
    /// </summary>
    public readonly System.Collections.Generic.List<CBuffEffect> BuffEffects;
    /// <summary>
    /// 作用目标
    /// </summary>
    public readonly ETargetType TargetType;
    /// <summary>
    /// 触发类型
    /// </summary>
    public readonly ETriggerType TriggerType;
    /// <summary>
    /// 状态ID
    /// </summary>
    public readonly int StatusId;
    public battle.StatuConfig StatusId_Ref;
    /// <summary>
    /// 目标参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> TargetParams;
    /// <summary>
    /// 触发参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> ConditionParams;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 触发间隔
    /// </summary>
    public readonly float TickInterval;
    /// <summary>
    /// 最大叠加层数
    /// </summary>
    public readonly int MaxStacks;
   
    public const int __ID__ = -2131067765;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BuffEffects) { _e?.ResolveRef(tables); }
        StatusId_Ref = tables.TbStatus.GetOrDefault(StatusId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "buffEffects:" + Luban.StringUtil.CollectionToString(BuffEffects) + ","
        + "targetType:" + TargetType + ","
        + "triggerType:" + TriggerType + ","
        + "statusId:" + StatusId + ","
        + "targetParams:" + Luban.StringUtil.CollectionToString(TargetParams) + ","
        + "conditionParams:" + Luban.StringUtil.CollectionToString(ConditionParams) + ","
        + "duration:" + Duration + ","
        + "tickInterval:" + TickInterval + ","
        + "maxStacks:" + MaxStacks + ","
        + "}";
    }
}
}

