
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BulletConfig : Luban.BeanBase
{
    public BulletConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        BulletType = (EBulletType)_buf.ReadInt();
        SpawnUnitId = _buf.ReadInt();
        SpawnUnitId_Ref = null;
        Damage = _buf.ReadInt();
        DebuffValue = _buf.ReadFloat();
    }

    public static BulletConfig DeserializeBulletConfig(ByteBuf _buf)
    {
        return new battle.BulletConfig(_buf);
    }

    /// <summary>
    /// 子弹id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 子弹类型
    /// </summary>
    public readonly EBulletType BulletType;
    /// <summary>
    /// 生成单位id
    /// </summary>
    public readonly int SpawnUnitId;
    public battle.UnitConfig SpawnUnitId_Ref;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 减益数值
    /// </summary>
    public readonly float DebuffValue;
   
    public const int __ID__ = -349657990;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SpawnUnitId_Ref = tables.TbUnit.GetOrDefault(SpawnUnitId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "bulletType:" + BulletType + ","
        + "spawnUnitId:" + SpawnUnitId + ","
        + "damage:" + Damage + ","
        + "debuffValue:" + DebuffValue + ","
        + "}";
    }
}
}

