
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class BulletConfig : Luban.BeanBase
{
    public BulletConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        BulletType = (EBulletType)_buf.ReadInt();
        DebuffDuration = _buf.ReadFloat();
        Speed = _buf.ReadFloat();
        Damages = global::GameConfig.CDamageEffect.DeserializeCDamageEffect(_buf);
        Buffs = _buf.ReadInt();
        Buffs_Ref = null;
        PreCastAnimTime = _buf.ReadFloat();
        PostCastAnimTime = _buf.ReadFloat();
        ModelId = _buf.ReadInt();
        ModelId_Ref = null;
    }

    public static BulletConfig DeserializeBulletConfig(ByteBuf _buf)
    {
        return new battle.BulletConfig(_buf);
    }

    /// <summary>
    /// 子弹id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 子弹类型
    /// </summary>
    public readonly EBulletType BulletType;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float DebuffDuration;
    /// <summary>
    /// 飞行速度
    /// </summary>
    public readonly float Speed;
    public readonly CDamageEffect Damages;
    /// <summary>
    /// 施加buff
    /// </summary>
    public readonly int Buffs;
    public battle.BuffConfig Buffs_Ref;
    /// <summary>
    /// 前摇动画间隔
    /// </summary>
    public readonly float PreCastAnimTime;
    /// <summary>
    /// 后摇动画间隔
    /// </summary>
    public readonly float PostCastAnimTime;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly int ModelId;
    public res.ModelConfig ModelId_Ref;
   
    public const int __ID__ = -349657990;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Damages?.ResolveRef(tables);
        Buffs_Ref = tables.TbBuff.GetOrDefault(Buffs);
        ModelId_Ref = tables.TbModel.GetOrDefault(ModelId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "bulletType:" + BulletType + ","
        + "debuffDuration:" + DebuffDuration + ","
        + "speed:" + Speed + ","
        + "damages:" + Damages + ","
        + "buffs:" + Buffs + ","
        + "preCastAnimTime:" + PreCastAnimTime + ","
        + "postCastAnimTime:" + PostCastAnimTime + ","
        + "modelId:" + ModelId + ","
        + "}";
    }
}
}

