
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class StatuConfig : Luban.BeanBase
{
    public StatuConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
    }

    public static StatuConfig DeserializeStatuConfig(ByteBuf _buf)
    {
        return new battle.StatuConfig(_buf);
    }

    /// <summary>
    /// 状态ID
    /// </summary>
    public readonly int Id;
   
    public const int __ID__ = 1613353709;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "}";
    }
}
}

