
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public partial class TbBullet
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BulletConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.BulletConfig> _dataList;
    
    public TbBullet(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BulletConfig>();
        _dataList = new System.Collections.Generic.List<battle.BulletConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            battle.BulletConfig _v;
            _v = global::GameConfig.battle.BulletConfig.DeserializeBulletConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, battle.BulletConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<battle.BulletConfig> DataList => _dataList;

    public battle.BulletConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public battle.BulletConfig Get(int key) => _dataMap[key];
    public battle.BulletConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

