
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public partial class TbStatus
{
    private readonly System.Collections.Generic.Dictionary<int, battle.StatuConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.StatuConfig> _dataList;
    
    public TbStatus(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.StatuConfig>();
        _dataList = new System.Collections.Generic.List<battle.StatuConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            battle.StatuConfig _v;
            _v = global::GameConfig.battle.StatuConfig.DeserializeStatuConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, battle.StatuConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<battle.StatuConfig> DataList => _dataList;

    public battle.StatuConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public battle.StatuConfig Get(int key) => _dataMap[key];
    public battle.StatuConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

