
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public partial class TbUnit
{
    private readonly System.Collections.Generic.Dictionary<int, battle.UnitConfig> _dataMap;
    private readonly System.Collections.Generic.List<battle.UnitConfig> _dataList;
    
    public TbUnit(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.UnitConfig>();
        _dataList = new System.Collections.Generic.List<battle.UnitConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            battle.UnitConfig _v;
            _v = global::GameConfig.battle.UnitConfig.DeserializeUnitConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, battle.UnitConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<battle.UnitConfig> DataList => _dataList;

    public battle.UnitConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public battle.UnitConfig Get(int key) => _dataMap[key];
    public battle.UnitConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

