
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class TowerConfig : Luban.BeanBase
{
    public TowerConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        BulletId = _buf.ReadInt();
        BulletId_Ref = null;
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AttackInterals = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); AttackInterals.Add(_e0);}}
        PrefabPath = _buf.ReadString();
    }

    public static TowerConfig DeserializeTowerConfig(ByteBuf _buf)
    {
        return new battle.TowerConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 塔名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 子弹
    /// </summary>
    public readonly int BulletId;
    public battle.BulletConfig BulletId_Ref;
    /// <summary>
    /// 攻击间隔等级配置
    /// </summary>
    public readonly System.Collections.Generic.List<float> AttackInterals;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string PrefabPath;
   
    public const int __ID__ = 949782357;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BulletId_Ref = tables.TbBullet.GetOrDefault(BulletId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "bulletId:" + BulletId + ","
        + "attackInterals:" + Luban.StringUtil.CollectionToString(AttackInterals) + ","
        + "prefabPath:" + PrefabPath + ","
        + "}";
    }
}
}

