
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class UnitConfig : Luban.BeanBase
{
    public UnitConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        UnitType = (EUnitType)_buf.ReadInt();
        MaxHp = _buf.ReadInt();
    }

    public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
    {
        return new battle.UnitConfig(_buf);
    }

    /// <summary>
    /// 单位id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 单位类型
    /// </summary>
    public readonly EUnitType UnitType;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly int MaxHp;
   
    public const int __ID__ = -1328964356;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "unitType:" + UnitType + ","
        + "maxHp:" + MaxHp + ","
        + "}";
    }
}
}

