
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.battle
{
public sealed partial class UnitConfig : Luban.BeanBase
{
    public UnitConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        UnitType = (EUnitType)_buf.ReadInt();
        BulletId = _buf.ReadInt();
        BulletId_Ref = null;
        MaxHp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        AttackRange = _buf.ReadFloat();
        AttackInterval = _buf.ReadFloat();
        Defense = _buf.ReadInt();
        MoveSpeed = _buf.ReadFloat();
        ModelId = _buf.ReadInt();
        ModelId_Ref = null;
    }

    public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
    {
        return new battle.UnitConfig(_buf);
    }

    /// <summary>
    /// 单位id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 单位类型
    /// </summary>
    public readonly EUnitType UnitType;
    /// <summary>
    /// 子弹
    /// </summary>
    public readonly int BulletId;
    public battle.BulletConfig BulletId_Ref;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly float AttackRange;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// 防御力
    /// </summary>
    public readonly int Defense;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 模型
    /// </summary>
    public readonly int ModelId;
    public res.ModelConfig ModelId_Ref;
   
    public const int __ID__ = -1328964356;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BulletId_Ref = tables.TbBullet.GetOrDefault(BulletId);
        ModelId_Ref = tables.TbModel.GetOrDefault(ModelId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "unitType:" + UnitType + ","
        + "bulletId:" + BulletId + ","
        + "maxHp:" + MaxHp + ","
        + "attack:" + Attack + ","
        + "attackRange:" + AttackRange + ","
        + "attackInterval:" + AttackInterval + ","
        + "defense:" + Defense + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "modelId:" + ModelId + ","
        + "}";
    }
}
}

