
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.booty
{
public sealed partial class Booty : Luban.BeanBase
{
    public Booty(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SubId = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
        MianItemId = _buf.ReadInt();
        MianItemId_Ref = null;
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RewardList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RewardList.Add(_e0);}}
    }

    public static Booty DeserializeBooty(ByteBuf _buf)
    {
        return new booty.Booty(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 这是子id
    /// </summary>
    public readonly int SubId;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 主奖励
    /// </summary>
    public readonly int MianItemId;
    public item.Item MianItemId_Ref;
    public readonly System.Collections.Generic.List<int> RewardList;
    public System.Collections.Generic.List<item.Item> RewardList_Ref;
   
    public const int __ID__ = -1707076928;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        MianItemId_Ref = tables.TbItem.GetOrDefault(MianItemId);
        RewardList_Ref = new System.Collections.Generic.List<item.Item>();
        foreach (var _v in RewardList) { RewardList_Ref.Add(tables.TbItem.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "subId:" + SubId + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "mianItemId:" + MianItemId + ","
        + "rewardList:" + Luban.StringUtil.CollectionToString(RewardList) + ","
        + "}";
    }
}

}

