
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.booty
{
public partial class TbBooty
{
    private readonly System.Collections.Generic.List<booty.BootyConfig> _dataList;

    private System.Collections.Generic.Dictionary<int, booty.BootyConfig> _dataMap_id;
    private System.Collections.Generic.Dictionary<int, booty.BootyConfig> _dataMap_sub_id;

    public TbBooty(ByteBuf _buf)
    {
        _dataList = new System.Collections.Generic.List<booty.BootyConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            booty.BootyConfig _v;
            _v = global::GameConfig.booty.BootyConfig.DeserializeBootyConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMap_id = new System.Collections.Generic.Dictionary<int, booty.BootyConfig>();
        _dataMap_sub_id = new System.Collections.Generic.Dictionary<int, booty.BootyConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_sub_id.Add(_v.SubId, _v);
    }
    }

    public System.Collections.Generic.List<booty.BootyConfig> DataList => _dataList;

    public booty.BootyConfig GetById(int key) => _dataMap_id.TryGetValue(key, out booty.BootyConfig __v) ? __v : null;
    public booty.BootyConfig GetBySubId(int key) => _dataMap_sub_id.TryGetValue(key, out booty.BootyConfig __v) ? __v : null;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

