
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.funcConfig
{
public sealed partial class FuncConfig : Luban.BeanBase
{
    public FuncConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        FuncIcon = _buf.ReadInt();
        OpenLevel = _buf.ReadInt();
        OpenFunc = _buf.ReadInt();
        UnlockTip = _buf.ReadString();
        LockTip = _buf.ReadString();
    }

    public static FuncConfig DeserializeFuncConfig(ByteBuf _buf)
    {
        return new funcConfig.FuncConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 开放图标
    /// </summary>
    public readonly int FuncIcon;
    /// <summary>
    /// 开放等级
    /// </summary>
    public readonly int OpenLevel;
    /// <summary>
    /// 开放函数
    /// </summary>
    public readonly int OpenFunc;
    /// <summary>
    /// 解锁提示
    /// </summary>
    public readonly string UnlockTip;
    /// <summary>
    /// 未解锁提示
    /// </summary>
    public readonly string LockTip;
   
    public const int __ID__ = -1745017074;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "FuncIcon:" + FuncIcon + ","
        + "OpenLevel:" + OpenLevel + ","
        + "OpenFunc:" + OpenFunc + ","
        + "UnlockTip:" + UnlockTip + ","
        + "LockTip:" + LockTip + ","
        + "}";
    }
}
}

