
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.funcConfig
{
public partial class TbFuncConfig
{
    private readonly System.Collections.Generic.Dictionary<int, funcConfig.FuncConfig> _dataMap;
    private readonly System.Collections.Generic.List<funcConfig.FuncConfig> _dataList;
    
    public TbFuncConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, funcConfig.FuncConfig>();
        _dataList = new System.Collections.Generic.List<funcConfig.FuncConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            funcConfig.FuncConfig _v;
            _v = global::GameConfig.funcConfig.FuncConfig.DeserializeFuncConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, funcConfig.FuncConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<funcConfig.FuncConfig> DataList => _dataList;

    public funcConfig.FuncConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public funcConfig.FuncConfig Get(int key) => _dataMap[key];
    public funcConfig.FuncConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

