
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    public enum ColorQuality
    {
        /// <summary>
        /// 白, 最差品质
        /// </summary>
        WHITE = 1,
        /// <summary>
        /// 蓝, 蓝色的
        /// </summary>
        BLUE = 2,
        /// <summary>
        /// 紫, 紫色的
        /// </summary>
        PURPLE = 3,
        /// <summary>
        /// 红, 最高品质
        /// </summary>
        RED = 4,
    }

} 

