
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class CurrencyConfig : Luban.BeanBase
{
    public CurrencyConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Icon = _buf.ReadString();
        Item = _buf.ReadInt();
        Item_Ref = null;
        NotEnoughTip = _buf.ReadString();
    }

    public static CurrencyConfig DeserializeCurrencyConfig(ByteBuf _buf)
    {
        return new item.CurrencyConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 图标（货币栏的图标）
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 对应道具Id
    /// </summary>
    public readonly int Item;
    public item.ItemConfig Item_Ref;
    /// <summary>
    /// 货币不足提示
    /// </summary>
    public readonly string NotEnoughTip;
   
    public const int __ID__ = 106352398;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Item_Ref = tables.TbItem.GetOrDefault(Item);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "icon:" + Icon + ","
        + "item:" + Item + ","
        + "notEnoughTip:" + NotEnoughTip + ","
        + "}";
    }
}
}

