
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    public enum CurrencyType
    {
        /// <summary>
        /// 金币
        /// </summary>
        Coin = 1,
        /// <summary>
        /// 体力
        /// </summary>
        Energy = 2,
        /// <summary>
        /// 局内金币
        /// </summary>
        BattleCoin = 1001,
    }

} 

