
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Icon = _buf.ReadString();
        ItemType = (item.ItemType)_buf.ReadInt();
        Getways = _buf.ReadInt();
        Getways_Ref = null;
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new item.ItemConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 介绍
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly item.ItemType ItemType;
    /// <summary>
    /// 获取途径
    /// </summary>
    public readonly int Getways;
    public item.ItemGetWayConfig Getways_Ref;
   
    public const int __ID__ = 660665872;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Getways_Ref = tables.TbGetWay.GetOrDefault(Getways);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "itemType:" + ItemType + ","
        + "getways:" + Getways + ","
        + "}";
    }
}
}

