
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Icon = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ExchangeList = new System.Collections.Generic.List<item.ItemExchange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { item.ItemExchange _e0;  _e0 = global::GameConfig.item.ItemExchange.DeserializeItemExchange(_buf); ExchangeList.Add(_e0);}}
        Test = global::GameConfig.item.ItemExchange.DeserializeItemExchange(_buf);
        Getways = _buf.ReadInt();
        Getways_Ref = null;
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        return new item.Item(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 介绍
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    public readonly System.Collections.Generic.List<item.ItemExchange> ExchangeList;
    /// <summary>
    /// 道具兑换配置
    /// </summary>
    public readonly item.ItemExchange Test;
    /// <summary>
    /// 获取途径
    /// </summary>
    public readonly int Getways;
    public item.ItemGetWay Getways_Ref;
   
    public const int __ID__ = 2107285806;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ExchangeList) { _e?.ResolveRef(tables); }
        Test?.ResolveRef(tables);
        Getways_Ref = tables.TbGetWay.GetOrDefault(Getways);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "exchangeList:" + Luban.StringUtil.CollectionToString(ExchangeList) + ","
        + "test:" + Test + ","
        + "getways:" + Getways + ","
        + "}";
    }
}
}

