
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class ItemExchangeConfig : Luban.BeanBase
{
    public ItemExchangeConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        IsApplyImmediately = _buf.ReadBool();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ExchangeList = new System.Collections.Generic.List<item.ItemExchange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { item.ItemExchange _e0;  _e0 = global::GameConfig.item.ItemExchange.DeserializeItemExchange(_buf); ExchangeList.Add(_e0);}}
        Test = global::GameConfig.item.ItemExchange.DeserializeItemExchange(_buf);
    }

    public static ItemExchangeConfig DeserializeItemExchangeConfig(ByteBuf _buf)
    {
        return new item.ItemExchangeConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 兑换是否立即生效
    /// </summary>
    public readonly bool IsApplyImmediately;
    /// <summary>
    /// 道具兑换配置
    /// </summary>
    public readonly System.Collections.Generic.List<item.ItemExchange> ExchangeList;
    /// <summary>
    /// 道具兑换配置
    /// </summary>
    public readonly item.ItemExchange Test;
   
    public const int __ID__ = 1484151827;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ExchangeList) { _e?.ResolveRef(tables); }
        Test?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "isApplyImmediately:" + IsApplyImmediately + ","
        + "exchangeList:" + Luban.StringUtil.CollectionToString(ExchangeList) + ","
        + "test:" + Test + ","
        + "}";
    }
}
}

