
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    [System.Flags]
    public enum ItemType
    {
        /// <summary>
        /// 货币
        /// </summary>
        Currency = 1,
        /// <summary>
        /// 物品
        /// </summary>
        Goods = 2,
    }

} 

