
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 通用道具奖励
/// </summary>
public sealed partial class RewardData : Luban.BeanBase
{
    public RewardData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Num = _buf.ReadInt();
    }

    public static RewardData DeserializeRewardData(ByteBuf _buf)
    {
        return new item.RewardData(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具数量
    /// </summary>
    public readonly int Num;
   
    public const int __ID__ = 813918548;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "num:" + Num + ","
        + "}";
    }
}
}

