
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbGetWay
{
    private readonly System.Collections.Generic.Dictionary<int, item.ItemGetWayConfig> _dataMap;
    private readonly System.Collections.Generic.List<item.ItemGetWayConfig> _dataList;
    
    public TbGetWay(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.ItemGetWayConfig>();
        _dataList = new System.Collections.Generic.List<item.ItemGetWayConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            item.ItemGetWayConfig _v;
            _v = global::GameConfig.item.ItemGetWayConfig.DeserializeItemGetWayConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.ItemGetWayConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<item.ItemGetWayConfig> DataList => _dataList;

    public item.ItemGetWayConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.ItemGetWayConfig Get(int key) => _dataMap[key];
    public item.ItemGetWayConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

