// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: base.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from base.proto</summary>
public static partial class BaseReflection {

  #region Descriptor
  /// <summary>File descriptor for base.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BaseReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpiYXNlLnByb3RvIkkKDFByb3RvUmVxdWVzdBITCgtwcm90b2NvbF9pZBgB",
          "IAEoDRITCgtzZXF1ZW5jZV9pZBgCIAEoBBIPCgdtZXNzYWdlGAMgASgMInEK",
          "DVByb3RvUmVzcG9uc2USEwoLcHJvdG9jb2xfaWQYASABKA0SEwoLc2VxdWVu",
          "Y2VfaWQYAiABKAQSEgoKZXJyb3JfY29kZRgDIAEoBRIRCgllcnJvcl9tc2cY",
          "BCABKAkSDwoHbWVzc2FnZRgFIAEoDGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoRequest), global::ProtoRequest.Parser, new[]{ "ProtocolId", "SequenceId", "Message" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoResponse), global::ProtoResponse.Parser, new[]{ "ProtocolId", "SequenceId", "ErrorCode", "ErrorMsg", "Message" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ProtoRequest : pb::IMessage<ProtoRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoRequest> _parser = new pb::MessageParser<ProtoRequest>(() => new ProtoRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BaseReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoRequest(ProtoRequest other) : this() {
    protocolId_ = other.protocolId_;
    sequenceId_ = other.sequenceId_;
    message_ = other.message_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoRequest Clone() {
    return new ProtoRequest(this);
  }

  /// <summary>Field number for the "protocol_id" field.</summary>
  public const int ProtocolIdFieldNumber = 1;
  private uint protocolId_;
  /// <summary>
  /// 协议ID，标识业务类型（如登录、支付）
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ProtocolId {
    get { return protocolId_; }
    set {
      protocolId_ = value;
    }
  }

  /// <summary>Field number for the "sequence_id" field.</summary>
  public const int SequenceIdFieldNumber = 2;
  private ulong sequenceId_;
  /// <summary>
  /// 请求序列号，客户端生成，唯一标识本次请求
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong SequenceId {
    get { return sequenceId_; }
    set {
      sequenceId_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 3;
  private pb::ByteString message_ = pb::ByteString.Empty;
  /// <summary>
  /// 业务参数（Protobuf/JSON序列化数据）
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ProtocolId != other.ProtocolId) return false;
    if (SequenceId != other.SequenceId) return false;
    if (Message != other.Message) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ProtocolId != 0) hash ^= ProtocolId.GetHashCode();
    if (SequenceId != 0UL) hash ^= SequenceId.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ProtocolId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(ProtocolId);
    }
    if (SequenceId != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(SequenceId);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ProtocolId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(ProtocolId);
    }
    if (SequenceId != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(SequenceId);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ProtocolId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtocolId);
    }
    if (SequenceId != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SequenceId);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Message);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoRequest other) {
    if (other == null) {
      return;
    }
    if (other.ProtocolId != 0) {
      ProtocolId = other.ProtocolId;
    }
    if (other.SequenceId != 0UL) {
      SequenceId = other.SequenceId;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ProtocolId = input.ReadUInt32();
          break;
        }
        case 16: {
          SequenceId = input.ReadUInt64();
          break;
        }
        case 26: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ProtocolId = input.ReadUInt32();
          break;
        }
        case 16: {
          SequenceId = input.ReadUInt64();
          break;
        }
        case 26: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ProtoResponse : pb::IMessage<ProtoResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoResponse> _parser = new pb::MessageParser<ProtoResponse>(() => new ProtoResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BaseReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoResponse(ProtoResponse other) : this() {
    protocolId_ = other.protocolId_;
    sequenceId_ = other.sequenceId_;
    errorCode_ = other.errorCode_;
    errorMsg_ = other.errorMsg_;
    message_ = other.message_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoResponse Clone() {
    return new ProtoResponse(this);
  }

  /// <summary>Field number for the "protocol_id" field.</summary>
  public const int ProtocolIdFieldNumber = 1;
  private uint protocolId_;
  /// <summary>
  /// 与请求的协议ID一致
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ProtocolId {
    get { return protocolId_; }
    set {
      protocolId_ = value;
    }
  }

  /// <summary>Field number for the "sequence_id" field.</summary>
  public const int SequenceIdFieldNumber = 2;
  private ulong sequenceId_;
  /// <summary>
  /// 原样返回请求的序列号
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong SequenceId {
    get { return sequenceId_; }
    set {
      sequenceId_ = value;
    }
  }

  /// <summary>Field number for the "error_code" field.</summary>
  public const int ErrorCodeFieldNumber = 3;
  private int errorCode_;
  /// <summary>
  /// 错误码（0=成功，非0=失败）
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ErrorCode {
    get { return errorCode_; }
    set {
      errorCode_ = value;
    }
  }

  /// <summary>Field number for the "error_msg" field.</summary>
  public const int ErrorMsgFieldNumber = 4;
  private string errorMsg_ = "";
  /// <summary>
  /// 错误详情（如“用户不存在”）
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ErrorMsg {
    get { return errorMsg_; }
    set {
      errorMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 5;
  private pb::ByteString message_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ProtocolId != other.ProtocolId) return false;
    if (SequenceId != other.SequenceId) return false;
    if (ErrorCode != other.ErrorCode) return false;
    if (ErrorMsg != other.ErrorMsg) return false;
    if (Message != other.Message) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ProtocolId != 0) hash ^= ProtocolId.GetHashCode();
    if (SequenceId != 0UL) hash ^= SequenceId.GetHashCode();
    if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
    if (ErrorMsg.Length != 0) hash ^= ErrorMsg.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ProtocolId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(ProtocolId);
    }
    if (SequenceId != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(SequenceId);
    }
    if (ErrorCode != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ErrorCode);
    }
    if (ErrorMsg.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ErrorMsg);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(42);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ProtocolId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(ProtocolId);
    }
    if (SequenceId != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(SequenceId);
    }
    if (ErrorCode != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ErrorCode);
    }
    if (ErrorMsg.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ErrorMsg);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(42);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ProtocolId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtocolId);
    }
    if (SequenceId != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SequenceId);
    }
    if (ErrorCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
    }
    if (ErrorMsg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMsg);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Message);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoResponse other) {
    if (other == null) {
      return;
    }
    if (other.ProtocolId != 0) {
      ProtocolId = other.ProtocolId;
    }
    if (other.SequenceId != 0UL) {
      SequenceId = other.SequenceId;
    }
    if (other.ErrorCode != 0) {
      ErrorCode = other.ErrorCode;
    }
    if (other.ErrorMsg.Length != 0) {
      ErrorMsg = other.ErrorMsg;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ProtocolId = input.ReadUInt32();
          break;
        }
        case 16: {
          SequenceId = input.ReadUInt64();
          break;
        }
        case 24: {
          ErrorCode = input.ReadInt32();
          break;
        }
        case 34: {
          ErrorMsg = input.ReadString();
          break;
        }
        case 42: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ProtocolId = input.ReadUInt32();
          break;
        }
        case 16: {
          SequenceId = input.ReadUInt64();
          break;
        }
        case 24: {
          ErrorCode = input.ReadInt32();
          break;
        }
        case 34: {
          ErrorMsg = input.ReadString();
          break;
        }
        case 42: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
