// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: prototype.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from prototype.proto</summary>
public static partial class PrototypeReflection {

  #region Descriptor
  /// <summary>File descriptor for prototype.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PrototypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9wcm90b3R5cGUucHJvdG8qegoMUHJvdG9jb2xUeXBlEggKBE5vbmUQABIS",
          "Cg1MT0dJTl9SRVFVRVNUEJFOEhMKDkxPR0lOX1JFU1BPTlNFEJJOEhAKC0NI",
          "QVRfTk9USUZZEJNOEhEKDENIQVRfUkVRVUVTVBCUThISCg1DSEFUX1JFU1BP",
          "TlNFEJVOYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtocolType), }, null, null));
  }
  #endregion

}
#region Enums
public enum ProtocolType {
  [pbr::OriginalName("None")] None = 0,
  [pbr::OriginalName("LOGIN_REQUEST")] LoginRequest = 10001,
  [pbr::OriginalName("LOGIN_RESPONSE")] LoginResponse = 10002,
  [pbr::OriginalName("CHAT_NOTIFY")] ChatNotify = 10003,
  [pbr::OriginalName("CHAT_REQUEST")] ChatRequest = 10004,
  [pbr::OriginalName("CHAT_RESPONSE")] ChatResponse = 10005,
}

#endregion


#endregion Designer generated code
