//------------------------------------------------------------------------------
//	<auto-generated>
//		This code was generated by autoBindTool.
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
//	</auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using AION.CoreFramework;

namespace GameLogic
{
	public partial class IBattleEvent_Event
	{
		public static readonly int OnBattleStart = RuntimeId.ToRuntimeId("IBattleEvent_Event.OnBattleStart");
		public static readonly int OnBattleEnd = RuntimeId.ToRuntimeId("IBattleEvent_Event.OnBattleEnd");
	}

	public partial class IBattleEvent_Gen : IBattleEvent
	{
		private EventDispatcher _dispatcher;
		public IBattleEvent_Gen(EventDispatcher dispatcher)
		{
			_dispatcher = dispatcher;
			GameEvent.EventMgr.RegWrapInterface("IBattleEvent", this);
		}

        public void OnBattleStart()
        {
            _dispatcher.Send(IBattleEvent_Event.OnBattleStart);
        }

        public void OnBattleEnd()
        {
            _dispatcher.Send(IBattleEvent_Event.OnBattleEnd);
        }

	}
}
