//------------------------------------------------------------------------------
//	<auto-generated>
//		This code was generated by autoBindTool.
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
//	</auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using AION.CoreFramework;

namespace GameLogic
{
	public partial class ICommonUI_Event
	{
		public static readonly int ShowTip = RuntimeId.ToRuntimeId("ICommonUI_Event.ShowTip");
		public static readonly int ShowError = RuntimeId.ToRuntimeId("ICommonUI_Event.ShowError");
		public static readonly int ShowReward = RuntimeId.ToRuntimeId("ICommonUI_Event.ShowReward");
		public static readonly int ShowAnnouncement = RuntimeId.ToRuntimeId("ICommonUI_Event.ShowAnnouncement");
	}

	public partial class ICommonUI_Gen : ICommonUI
	{
		private EventDispatcher _dispatcher;
		public ICommonUI_Gen(EventDispatcher dispatcher)
		{
			_dispatcher = dispatcher;
			GameEvent.EventMgr.RegWrapInterface("ICommonUI", this);
		}

        public void ShowTip(System.String tip)
        {
            _dispatcher.Send(ICommonUI_Event.ShowTip,tip);
        }

        public void ShowError(System.String error)
        {
            _dispatcher.Send(ICommonUI_Event.ShowError,error);
        }

        public void ShowReward(RewardData reward)
        {
	        
        }
     
        public void ShowAnnouncement(System.String announcement)
        {
            _dispatcher.Send(ICommonUI_Event.ShowAnnouncement,announcement);
        }

	}
}
