//------------------------------------------------------------------------------
//	<auto-generated>
//		This code was generated by autoBindTool.
//		Changes to this file may cause incorrect behavior and will be lost if
//		the code is regenerated.
//	</auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using AION.CoreFramework;

namespace GameLogic
{
	public partial class INumeric_Event
	{
	}

	public partial class INumeric_Gen : INumeric
	{
		private EventDispatcher _dispatcher;
		public INumeric_Gen(EventDispatcher dispatcher)
		{
			_dispatcher = dispatcher;
			GameEvent.EventMgr.RegWrapInterface("INumeric", this);
		}

	}
}
