
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public sealed partial class LevelBaseConfig : Luban.BeanBase
{
    public LevelBaseConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);WaveIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); WaveIds.Add(_e0);}}
        BaseHp = _buf.ReadInt();
        RewardGold = _buf.ReadInt();
        UnlockNextLevel = _buf.ReadInt();
    }

    public static LevelBaseConfig DeserializeLevelBaseConfig(ByteBuf _buf)
    {
        return new level.LevelBaseConfig(_buf);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 波次ID列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> WaveIds;
    /// <summary>
    /// 基地生命
    /// </summary>
    public readonly int BaseHp;
    /// <summary>
    /// 奖励金币
    /// </summary>
    public readonly int RewardGold;
    /// <summary>
    /// 解锁下一关
    /// </summary>
    public readonly int UnlockNextLevel;
   
    public const int __ID__ = 1534124429;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "waveIds:" + Luban.StringUtil.CollectionToString(WaveIds) + ","
        + "baseHp:" + BaseHp + ","
        + "rewardGold:" + RewardGold + ","
        + "unlockNextLevel:" + UnlockNextLevel + ","
        + "}";
    }
}
}

