
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public partial class TbLevelBase
{
    private readonly System.Collections.Generic.Dictionary<int, level.LevelBaseConfig> _dataMap;
    private readonly System.Collections.Generic.List<level.LevelBaseConfig> _dataList;
    
    public TbLevelBase(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, level.LevelBaseConfig>();
        _dataList = new System.Collections.Generic.List<level.LevelBaseConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            level.LevelBaseConfig _v;
            _v = global::GameConfig.level.LevelBaseConfig.DeserializeLevelBaseConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, level.LevelBaseConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<level.LevelBaseConfig> DataList => _dataList;

    public level.LevelBaseConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.LevelBaseConfig Get(int key) => _dataMap[key];
    public level.LevelBaseConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

