
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public sealed partial class WaveConfig : Luban.BeanBase
{
    public WaveConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        WaveIndex = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SpawnGroups = new System.Collections.Generic.List<SpawnGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { SpawnGroup _e0;  _e0 = global::GameConfig.SpawnGroup.DeserializeSpawnGroup(_buf); SpawnGroups.Add(_e0);}}
    }

    public static WaveConfig DeserializeWaveConfig(ByteBuf _buf)
    {
        return new level.WaveConfig(_buf);
    }

    /// <summary>
    /// 波次ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 波次索引
    /// </summary>
    public readonly int WaveIndex;
    /// <summary>
    /// 波次名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 生成组列表(JSON格式，多个用;分隔)
    /// </summary>
    public readonly System.Collections.Generic.List<SpawnGroup> SpawnGroups;
   
    public const int __ID__ = 1060694117;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SpawnGroups) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "waveIndex:" + WaveIndex + ","
        + "name:" + Name + ","
        + "spawnGroups:" + Luban.StringUtil.CollectionToString(SpawnGroups) + ","
        + "}";
    }
}
}

