
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class CBuffEffect : Luban.BeanBase
{
    public CBuffEffect(ByteBuf _buf) 
    {
        Type = (EBuffType)_buf.ReadInt();
        DamageType = (EDamageType)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ValueParams = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); ValueParams.Add(_e0);}}
    }

    public static CBuffEffect DeserializeCBuffEffect(ByteBuf _buf)
    {
        return new CBuffEffect(_buf);
    }

    public readonly EBuffType Type;
    /// <summary>
    /// 伤害类型
    /// </summary>
    public readonly EDamageType DamageType;
    /// <summary>
    /// buff参数，根据buff类型不同而不同
    /// </summary>
    public readonly System.Collections.Generic.List<float> ValueParams;
   
    public const int __ID__ = -1458581401;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "damageType:" + DamageType + ","
        + "valueParams:" + Luban.StringUtil.CollectionToString(ValueParams) + ","
        + "}";
    }
}
}

