
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class CDamageEffect : Luban.BeanBase
{
    public CDamageEffect(ByteBuf _buf) 
    {
        Type = (EDamageType)_buf.ReadInt();
        Value = _buf.ReadFloat();
    }

    public static CDamageEffect DeserializeCDamageEffect(ByteBuf _buf)
    {
        return new CDamageEffect(_buf);
    }

    public readonly EDamageType Type;
    /// <summary>
    /// 伤害值
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = 961522115;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

