
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EBuffType
    {
        /// <summary>
        /// 属性修改：提升或降低目标属性（如攻击力）
        /// </summary>
        PropertyMod = 1,
        /// <summary>
        /// 治疗：恢复目标生命值
        /// </summary>
        Heal = 2,
        /// <summary>
        /// 伤害：对目标造成伤害
        /// </summary>
        Damage = 3,
        /// <summary>
        /// 状态：施加特殊状态（如眩晕、击退）
        /// </summary>
        Status = 4,
        /// <summary>
        /// 子弹属性修改
        /// </summary>
        BulletPropertyMod = 5,
        /// <summary>
        /// 塔属性修改
        /// </summary>
        TowerPropertyMod = 6,
    }

} 

