
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EBulletType
    {
        NONE = 0,
        MELEE = 1,
        PROJECTILE = 2,
        SPAWN_UNIT = 3,
    }

} 

