
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EDamageType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 物理伤害
        /// </summary>
        Physical = 1,
        /// <summary>
        /// 魔法伤害
        /// </summary>
        Magical = 2,
        /// <summary>
        /// 真实伤害，无视护甲和魔抗
        /// </summary>
        True = 3,
        /// <summary>
        /// 火焰伤害（燃烧箭矢、火球、陨石）
        /// </summary>
        Fire = 4,
        /// <summary>
        /// 冰霜伤害（冰箭矢、冰冻效果）
        /// </summary>
        Ice = 5,
        /// <summary>
        /// 雷电伤害（闪电链、落雷、麻痹）
        /// </summary>
        Lightning = 6,
        /// <summary>
        /// 神圣伤害（光塔的圣光）
        /// </summary>
        Holy = 7,
        /// <summary>
        /// 毒素伤害（中毒持续伤害）
        /// </summary>
        Poison = 8,
        /// <summary>
        /// 流血伤害（物理系持续伤害）
        /// </summary>
        Bleed = 9,
    }

} 

