
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ETriggerType
    {
        /// <summary>
        /// 立即触发：Buff生效时立即触发一次效果
        /// </summary>
        Immediate = 1,
        /// <summary>
        /// 间隔触发：按固定时间间隔周期性触发效果
        /// </summary>
        Interval = 2,
        /// <summary>
        /// 概率触发：满足条件时按一定概率触发效果
        /// </summary>
        Probability = 3,
    }

} 

