
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    [System.Flags]
    public enum FuncType
    {
        /// <summary>
        /// 装备
        /// </summary>
        FUNC_MAIN_EQUIP = 1,
        /// <summary>
        /// 背包
        /// </summary>
        FUNC_MAIN_BAG = 2,
        /// <summary>
        /// 深渊挑战
        /// </summary>
        FUNC_MAIN_SHENYUAN_CHALLENGE = 3,
        /// <summary>
        /// 英雄试炼
        /// </summary>
        FUNC_MAIN_HERO_CHALENGE = 4,
        /// <summary>
        /// 竞技场
        /// </summary>
        FUNC_MAIN_JJC = 5,
        /// <summary>
        /// 家园
        /// </summary>
        FUNC_MAIN_FARM = 6,
        /// <summary>
        /// 商店
        /// </summary>
        FUNC_MAIN_SHOP = 7,
    }

} 

