
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class SpawnGroup : Luban.BeanBase
{
    public SpawnGroup(ByteBuf _buf) 
    {
        UnitId = _buf.ReadInt();
        SpawnCount = _buf.ReadInt();
        SpawnInterval = _buf.ReadFloat();
        SpawnDelay = _buf.ReadFloat();
    }

    public static SpawnGroup DeserializeSpawnGroup(ByteBuf _buf)
    {
        return new SpawnGroup(_buf);
    }

    /// <summary>
    /// 敌人单位ID（引用UnitConfig）
    /// </summary>
    public readonly int UnitId;
    /// <summary>
    /// 生成数量
    /// </summary>
    public readonly int SpawnCount;
    /// <summary>
    /// 生成间隔（秒）
    /// </summary>
    public readonly float SpawnInterval;
    /// <summary>
    /// 延迟开始生成时间（秒）
    /// </summary>
    public readonly float SpawnDelay;
   
    public const int __ID__ = -991239196;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "unitId:" + UnitId + ","
        + "spawnCount:" + SpawnCount + ","
        + "spawnInterval:" + SpawnInterval + ","
        + "spawnDelay:" + SpawnDelay + ","
        + "}";
    }
}
}

