
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public booty.TbBooty TbBooty {get; }
    public funcConfig.TbFunc TbFunc {get; }
    public item.TbGetWay TbGetWay {get; }
    public item.TbCurrency TbCurrency {get; }
    public item.TbItemExchange TbItemExchange {get; }
    public battle.TbTower TbTower {get; }
    public battle.TbBullet TbBullet {get; }
    public battle.TbUnit TbUnit {get; }
    public battle.TbBuff TbBuff {get; }
    public battle.TbStatus TbStatus {get; }
    public level.TbLevelBase TbLevelBase {get; }
    public level.TbWave TbWave {get; }
    public res.TbModel TbModel {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbBooty = new booty.TbBooty(loader("booty_tbbooty"));
        TbFunc = new funcConfig.TbFunc(loader("funcconfig_tbfunc"));
        TbGetWay = new item.TbGetWay(loader("item_tbgetway"));
        TbCurrency = new item.TbCurrency(loader("item_tbcurrency"));
        TbItemExchange = new item.TbItemExchange(loader("item_tbitemexchange"));
        TbTower = new battle.TbTower(loader("battle_tbtower"));
        TbBullet = new battle.TbBullet(loader("battle_tbbullet"));
        TbUnit = new battle.TbUnit(loader("battle_tbunit"));
        TbBuff = new battle.TbBuff(loader("battle_tbbuff"));
        TbStatus = new battle.TbStatus(loader("battle_tbstatus"));
        TbLevelBase = new level.TbLevelBase(loader("level_tblevelbase"));
        TbWave = new level.TbWave(loader("level_tbwave"));
        TbModel = new res.TbModel(loader("res_tbmodel"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbBooty.ResolveRef(this);
        TbFunc.ResolveRef(this);
        TbGetWay.ResolveRef(this);
        TbCurrency.ResolveRef(this);
        TbItemExchange.ResolveRef(this);
        TbTower.ResolveRef(this);
        TbBullet.ResolveRef(this);
        TbUnit.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbStatus.ResolveRef(this);
        TbLevelBase.ResolveRef(this);
        TbWave.ResolveRef(this);
        TbModel.ResolveRef(this);
    }
}

}
